Makefile, srcs/message/IRCMessage.hpp, srcs/message/IRCMessageParser.hpp, srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp, srcs/packet/packet.hpp, srcs/server/IRCServer.cpp, srcs/server/IRCServer.hpp, srcs/session/Session.cpp, srcs/session/Session.hpp, srcs/session/SessionManager.hpp, test/Makefile, test/parse.cpp
- IRCServer Parsing 구현
- IRCMessage
- :prefix command param ... :tailing
- IRCMessageParser
- request 데이터를 IRCMessage로 변환해 줍니다.
- PacketManager
- IRCMessage 입력받아 처리합니다.
=> [Feat] IRCServer Parsing 구현 #3

srcs/message/IRCMessage.hpp, srcs/message/IRCMessageParser.hpp, srcs/session/Session.cpp
- 파싱 split 자료형 수정 및 prefix 재추가
- 평가 항목에 nc 외에 reference irc client 테스트가 있어, prefix를 추가했습니다. (message를 수신 받을 때, 자동으로 추가해주는 client가 있다고 합니다)
- vector는 추가도리 때마다 비용이 크다고 하여, list로 바꾸었습니다.
=> [Fix] 파싱 split 자료형 수정 및 prefix 재추가 #3

srcs/message/IRCMessage.hpp, srcs/message/IRCMessageParser.hpp, srcs/session/Session.cpp
=> [feat] main merge to the branch

Makefile, srcs/message/IRCMessage.hpp, srcs/message/IRCMessageParser.hpp, srcs/packet/PacketCode.hpp, srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp, srcs/packet/packet.hpp, srcs/reactor/SocketReactor.hpp, srcs/server/IRCServer.cpp, srcs/server/IRCServer.hpp, srcs/session/Session.cpp, srcs/session/Session.hpp, srcs/session/SessionManager.cpp, srcs/session/SessionManager.hpp
- NICK 구현
- 뭔가 많아보이지만 헤더명 변경 때문입니다😵
- packetManager에서 command 처리하고 send 합니다. (동현님이 추후 session으로 빼고 싶은 마음 가득♨️)
- 앞으로 각자 command 구현하면 됨!
- 오옹 거의 다 한 것 같다!!🤼
=> [Feat] NICK 구현 #10

srcs/channel/Channel.cpp, srcs/channel/Channel.hpp, srcs/client/Client.cpp, srcs/client/Client.hpp, srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp
- NICK 수정시 속한 모든 채널의 모든 유저들에게 메시지 전송을 하기 위해 구현하였습니다.
- braodcastChannel : 해당 채널에 속한 유저들에게 브로드 캐스트 합니다.
- broadcastChannels : 관련 채널들에 속한 유저들에게 브로드 캐스트합니다.
=> [Feat] BroadCastChannel 구현 close #17

srcs/channel/Channel.cpp, srcs/channel/Channel.hpp, srcs/channel/ChannelManager.cpp, srcs/channel/ChannelManager.hpp, srcs/client/Client.cpp, srcs/client/Client.hpp, srcs/client/ClientManager.cpp, srcs/client/ClientManager.hpp, srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp
- JOIN 구현
- 인자가 하나인 지 → 461
- `#` , `&` 으로 시작하는 지 → 403
- 채널을 중복 요청한 것은 아닌지 → 443
- 존재하는 채널명인지, 아닌지
- 존재한다면:
- 유저 추가
- 아니라면:
- 새로운 채널 생성
- operator로 추가
- 채널 청취 시작 → 353, 유저리스트 send
=> [Feat] JOIN 구현 #19

srcs/client/Client.cpp, srcs/client/Client.hpp, srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp, srcs/server/IRCServer.cpp
- PASS 명령어 구현
- PASS 명령어는 서버에서 설정된 비밀번호와 맞는지 유효검사를 통하여 클라이언트가 소켓 연결을 하기 위해 사용됩니다.
- Server 에서 상태 값을 갖는 것 보다, 구조상 PacketManager 가 init 하는 부분에서 매개인자로 password 를 받아 초기화하고,
- 추후에 PASS 명령어를 사용할 때 그 명령어와 요구 매개 인자가 하나인지 ( 비밀번호만 받는 하나의 매개인자 ),
- 그 입력한 매개인자가 설정한 비밀번호가 맞는지를 확인하고, 그 후에 클라이언트의 속성에서 PASS 된 클라이언트인지 상태를 변경합니다.
- IrcServer :: init 함수에서 파라미터로 비밀번호를 받아서 PacketManager init에 전달합니다.
- PacketManager :: init 함수에 파라미터로 입력받은 비밀번호를 저장합니다.
- PacketManager :: processPass 함수에서 유효검사를 합니다. 
- Client 속성 IsPass 상태를 true로 바꾸는 setPassTrue 함수를 호출합니다.
- 추가) PacketManager :: isPass 속성 삭제와, ::processPass 함수 내 조건절 수정
=> [Fix] PASS수정 #13

srcs/channel/Channel.cpp, srcs/channel/Channel.hpp, srcs/client/Client.cpp, srcs/client/Client.hpp, srcs/client/ClientManager.cpp, srcs/client/ClientManager.hpp, srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp
- PRIVMSG 구현
```
req : PRIVMSG <targets> :<message>
res: :<prefix> PRIVMSG <target> :<message>
```
- target split() 후 message 전송
- <prefix> 에는 보낸 사람의 nickname이 들어갑니다.
- target에는 받는 사람의 nickname 혹은 channelName이 들어갑니다
- error 메시지
- target이 존재하지 않을 때 (== parameter가 0개 일때)
- parameter가 2개이상일때 (에러코드가 rfc에 안나와있는 것 같아서 어떻게 메시지를 보낼지 고민중…!)
- trailing(==message)이 없을 때
- 존재하지 않는 channel/client에게 보낼 때
- channel에 속해 있지 않은데 보낼 때
=> [Feat] PRIVMSG 구현 #20

srcs/packet/PacketManager.cpp
- 462 에러 코드 관련 추가 및 구현
- 이미 클라이언트가 PASS 인가를 통과했을 경우 또 한 번 비밀번호를 입력할 시 에러 코드 462를 반환합니다.
=> [feat] : 인가받은 클라이언트 462 코드 반환#29

srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp
- notice 구현
- privmsg와 같지만 에러메시지를 보내지 않습니다.
- `void PacketManager::broadcastChannelWithoutMe(int sessionIndex, Channel *channel, std::string &res)`를 추가했습니다.
=> [Feat] notice 구현 #33

srcs/client/Client.cpp, srcs/packet/Packet.hpp, srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp, srcs/server/IRCServer.cpp, srcs/server/IRCServer.hpp, srcs/session/Session.cpp, srcs/session/Session.hpp, srcs/session/SessionManager.cpp
- QUIT 명령어를 구현했습니다.
- EXIT 명령어가 왔을 경우에도 QUIT명령어가 실행됩니다.
- 클라이언트가 소켓을 끊었을 경우에도 QUIT 명령어가 실행됩니다.
- 인증(패스워드)에 성공했는지
- 가입된 채널의 해당 운영자 삭제
- 가입된 채널의 해당 클라이언트 삭제
- 클라이언트 매니저에서 해당 클라이언트 삭제
- 클라이언트 초기화 
- QUIT 명령어
```
C  ->  QUIT
S  <-  소켓종료
```
- 채널에 속해있는 다른 유저들에게 QUIT 알림
```
C  -> QUIT :bye~ bye~
S  <- :colin!colin@localhost QUIT : bye~ bye~
S  <- :colin!colin@localhost QUIT : bye~ bye~
```
=> [Feat] QUIT 구현 close #35

srcs/channel/ChannelManager.cpp, srcs/channel/ChannelManager.hpp, srcs/client/ClientManager.cpp, srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp
- part 구현
- part 구현 했습니다!
```
if (req._parameters.size() != 1) // 인자가 하나인 지 → 461
for (...) {
if (!channel                           // 존재하는 채널인지(유효성 검사도 여기서 한번에!) → 403
if (!_clientManager.isJoinedChannel    // 유저가 들어있는 채널에 나가는 걸 요청한건 지 → 442
leaveClient  // 나가기                    
// 해당 클라이언트에 RPL_PART 보내줌
// 채널에 남아있는 사람들에게도 RPL_PART 보내줌
}
```
```
C  ->  part #alpha,#charlie
S <-   :patty!p@localhost PART #alpha
S <-   :patty!p@localhost PART #charlie
모던독스에 따르면 서버에서 메시지에 mulyiple channel 처리를 하지 말라고 명시되어 있습니다. 그래서 하나씩 처리함!:)
```
- ‼️ 현재 irssi에서 part 입력에 대한 응답을 받으면, 명단은 갱신이 되는데 방에서는 안 나가지는 문제가 있습니다. (이틀동안 이것저것 해보았지만... 풀리지 않는,,,🥲)
- 혹시 입장부터 문제가 있나 싶어 join을수정하고 다시 고쳐보겠습니다. 엉엉😭
=> [Feat] part 구현 #31

srcs/client/Client.hpp, srcs/packet/PacketManager.cpp
- User를 구현했습니다.
- 인증(패스워드) 확인
- 파라미터 개수(3) 확인
- 유저 재등록 확인
- 클라이언트 Username, Hostname, Servername, Realname 등록
=> [Feat] User 구현 #37

srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp
- kick구현
KICK 로직
- 파람 수 체크 → 461
- `#` , `&` 으로 시작하는 지, 존재하는 채널인지 → 403
- 명령어를 사용한 유저가 채널에 있는지 → 442
- 명령어를 사용한 유저가 channel operator인지 → 482 (채널 생성자가 채널 운영자임 *모던독스 ChannelType)
- 강퇴대상자가 여러명일 수 있습니다. for문을 돌며 확인합니다.
- 강퇴 대상자가 채널에 있는지 → 441
- 명령을 요청한 사람과 채널내에 있는 사람들, 강퇴 대상자에게 RPL_KICK 보내줌 (이때, tailing이 없으면 기본 메시지를 사용해야 함 *모던 독스 KICK)
=> [Feat] kick구현#22

srcs/channel/Channel.cpp, srcs/channel/Channel.hpp, srcs/channel/ChannelManager.cpp, srcs/channel/ChannelManager.hpp, srcs/channel/ChannelMode.hpp, srcs/packet/PacketManager.cpp, srcs/packet/PacketManager.hpp
- MODE 기능을 구현했습니다.
- MODE 옵션
- `+i` : 오직 초대만으로만 채널 입장 가능
- `-i` : 제한없이 채널 입장 가능
- `+t` : 채널 토픽 수정 가능
- `-t` : 채널 토픽 수정 불가능
- `+k` : 방 패스워드 설정
- `-k` : 방 패스워드 해제
- `+o` : 채널 오퍼레이터 지정
- `-o` : 채널 오퍼레이터 지정 해제
- `+l` : 채널 인원수 제한
- `-l` : 채널 인원수 제한 해제
=> [Feat] MODE구현 close #49

srcs/main.cpp, srcs/server/IRCServer.cpp, srcs/server/IRCServer.hpp, srcs/socket/ServerSocket.cpp, srcs/socket/ServerSocket.hpp
=> [Feat] PORT 설정 close #54

srcs/client/ClientManager.cpp, srcs/reactor/SocketReactor.tpp, srcs/server/IRCServer.cpp
- 일부 기능 수정
- errno를 에러 문자열로 출력할 수 있도록 수정
- 세션 할당 실패시(Session 생성 실패, 유저수 초과) 연결된 소켓 끊기
=> [Fix] 일부 기능 수정 #57

srcs/socket/ServerSocket.cpp
- sockaddr_in 구조체 초기화
- 지정해주지 않는 부분은 0으로 초기화가 필요하다고 합니다.
=> [Feat] 주소 초기화 추가

srcs/message/IRCMessage.cpp, srcs/message/IRCMessage.hpp, srcs/packet/PacketManager.cpp
- 요청 명령어 처리시, leak 누수 해결
- memset 호출시, vector 내부에 동적할당된 포인터 주소가 NULL이 되어 메모리 해제가 이루어지지 않음
- memset 대신 IRCMessage 멤버함수로 clear()를 만듬
=> [Fix] leak누수해결 close #60

srcs/message/IRCMessage.cpp, srcs/message/IRCMessage.hpp, srcs/session/Session.cpp, srcs/session/Session.hpp
- partial command 처리 
- 기존에 있던 _buffer[512] -> _tmp[512] 변경 : recv() 읽기 용도
- stringstream _buffer 추가 : 캐리지리턴을 만나기 전까지 담아두는 용도
=> [Fix] partial command 처리 #62

srcs/channel/ChannelManager.hpp, srcs/channel/ChannelMode.hpp, srcs/client/ClientManager.hpp, srcs/message/IRCMessage.hpp, srcs/server/IRCServer.hpp, srcs/session/Session.cpp, srcs/session/Session.hpp, srcs/session/SessionManager.hpp
- 사용되지 않은 헤더 삭제했습니다.
- new 헤더 추가했습니다.
- 필요한 헤더파일은 아래 상황처럼 중복되더라도 명시적으로 추가했습니다
```c++
// Client.hpp
#include <list>
```
```c++
// ClientManager.hpp
#include <list>  <--- 명시적으로 추가  
#include <Client.hpp>
```
- 추가적으로 정리해야할 헤더파일이 더 있다면 코멘트 남겨주세요
=> [Fix] 헤더파일 정리 close #64

srcs/packet/PacketManager.cpp
- MODE 처리 수정
- JOIN 명령어 요청시, 채널명이 포함된 MODE명령어를 요청한다. ex) ```MODE #5```
이전 MODE처리시 파라미터가 부족한 것으로 판단하여 파라미터 부족 메시지를 보냈으나 메시지를 보내지 않는 것으로 바꿈
=> [Fix] MODE 처리 수정 close #66

srcs/channel/ChannelManager.hpp, srcs/server/IRCServer.cpp
- 클라이언트 소켓 논블록킹 적용
- INT_MAX 상수값을 담고있는 climits 헤더 추가
=> [Feat] 기능 추가   #68
